# Generated by Django 5.1.6 on 2025-03-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_sendsettings_alter_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaymessage',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='SendSettings',
        ),
        migrations.DeleteModel(
            name='BirthdayMessage',
        ),
    ]
